### ISSUE TITLE
Building with IDF

### ISSUE THREAD

**Issue by LsHallo** [cfint/esp32-a2dp-sink#1]
Hello,
first of all thank you for your effort you put into this project!

I wanted to try myself after using the original A2DP sink.
But I have never used espressif IDF and even less have i tried to use some custom version in conjunction with a project.
Could you provide some more detailed steps how to build this project?
Maybe even make it platformIO compatible so it is only a few clicks to set everything up?
Have been struggling for a few hours now and might need some help.

Steps I took so far:
Am I correct in using the `v4.4-a2dp-sink-codecs` branch in your IDF fork?
`git clone --branch v4.4-a2dp-sink-codecs git@github.com:cfint/esp-idf.git`
I then ran setup.ps1 and export.ps1. (submodules downloaded an py packages installed during these steps)
After that i opened a cmd and ran export.bat.
I then cloned this repo and made sure the submodule was also cloned correctly.
Back in my terminal I ran `idf.py build` but it complains about a missing `BluetoothA2DPSink.h`.

Paths:
C:\Users\LsHallo\idf_custom <- Your IDF fork
C:\Users\LsHallo\Documents\Projects\aptXSink <- This repo
C:\Users\LsHallo\Documents\Projects\aptXSink\components\ESP32-A2DP <- Your A2DP fork

Thanks in advance!

**Comment by LsHallo** [comment]
Needed to run `idf.py reconfigure`. Now compiles and flashes without issue.

**Comment by zylo117** [comment]
No, you should `git submodule update --init`, then it works. BluetoothA2DPSink.h is in the submodule
