### ISSUE TITLE
Just noise on I2S codec output with LDAC & AptX HD

### ISSUE THREAD

**Issue by MayaPosch** [cfint/esp32-a2dp-sink#2]
I built the project as indicated with the custom ESP-IDF project at https://github.com/cfint/esp-idf

Branch used is [v4.4-a2dp-sink-codecs-dev](https://github.com/cfint/esp-idf/tree/v4.4-a2dp-sink-codecs-dev).

After flashing the ESP32 (ESP-WROOM-32) module, on the UDA1334A I2S codec's output I can only hear noise, whether LDAC or AptX HD is selected in the Android phone's BT options for the connection. With the `master` branch SBC is selected as codec, but I also only hear noise.

On the same hardware the standard ESP-IDF A2DP sink example works fine, using the SBC codec.

What changes should be made to fix these issues?

**Comment by MayaPosch** [comment]
Closing this issue. I have resolved this for my situation by adapting the A2DP Sink example from the standard ESP-IDF to include LDAC & AptX support.

**Comment by gb160** [comment]
> Closing this issue. I have resolved this for my situation by adapting the A2DP Sink example from the standard ESP-IDF to include LDAC & AptX support.

I don't suppose you could give details on how you did this? It would be much appreciated.
